// This source file was auto-generated by ClassMate++
// Created: 1 Dec 2020 7:46:02 am
// Copyright (c) 2020, HurleyWorks

#include "Model.h"


// ctor
Model::Model ()
{	
}

// dtor
Model::~Model ()
{	
}

