// This header file was auto-generated by ClassMate++
// Created: 1 Dec 2020 7:46:02 am
// Copyright (c) 2020, HurleyWorks

#pragma once

#include <iostream>
// copper spice signal/slots
#include <cs_signal.h>
#include <cs_slot.h>

class Model : public CsSignal::SlotBase
{

 public:
	Model ();
	~Model ();
		
	void printMsg1(uint32_t id)
	{
		std::cout << "printing " <<  id << std::endl;
	}

	void printMsg2(uint32_t id)
	{
		std::cout << "printing " << id << std::endl;
	}

	void printMsg3(uint32_t id)
	{
		std::cout << "printing " << id << std::endl;
	}

	void printMsg4(uint32_t id)
	{
		std::cout << "printing " << id << std::endl;
	}

	void receive1()
	{
		std::cout << "receving 1" << std::endl;
	}
	void receive2()
	{
		std::cout << "receving 2" << std::endl;
	}
	void receive3()
	{
		std::cout << "receving 3" << std::endl;
	}
	void receive4()
	{
		std::cout << "receving 4" << std::endl;
	}

}; // end class Model
